version: "3"


services:
    currency-exchange:
        image: pavanbhagathi1234/mmv3-currency-exchange-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - 8000:8000
        networks:
            - currency-network
        depends_on:
            - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
         
            
    naming-server:
        image: pavanbhagathi1234/mmv3-naming-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - 8761:8761
        networks:
            - currency-network

    currency-conversion:
        image: pavanbhagathi1234/mmv3-currency-conversion-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - 8100:8100
        networks:
            - currency-network
        depends_on:
            - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
            
    api-gateway:
        image: pavanbhagathi1234/mmv3-apigateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - 8765:8765
        networks:
            - currency-network
        depends_on:
            - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
    
            
    zipkin-server:
        image: openzipkin/zipkin:2.23
        mem_limit: 300m
        ports:
            - 9411:9411
        networks:
            - currency-network
        depends_on:
            - rabbit-amq
            
            
    rabbit-amq: 
        image : rabbitmq:3.5.3-management
        mem_limit: 300m
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - currency-network
        
           
  
        
networks:
    currency-network: